### ISSUE TITLE
websocket库的选择

### ISSUE THREAD

**Issue by AshenOneYe** [snyssss/WFHelper-UI#1]
后端用flask-socketio可以和flask http server同时启动，这样可以少开一个端口，前端websocket的库就要用socket.io.js了，目前正在尝试修改

**Comment by snyssss** [comment]
这两天没时间摸，你放手去改吧。
我的初步打算是把请求指令也改成websocket请求，UI端未来增加一个地址配置项。
然后实时更新屏幕部分打算用mse-player。
